### ISSUE TITLE
Add support for config for each preset in an individual file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/preset#6]
The example of the image preset appears to store information for all the presets in the same config file. 

As a site manager, I prefer that each preset is stored in it's own individual file. When new presets are added to an existing site, I want to be able to add my config file, commit, and deploy, without the possibility of affecting an of the other presets. (This is how many ctools exportables work, as well as image styles, node types, and most config in core)

From the documentation, it appears that this might have been the original intent of preset (or, perhaps another supported option?) but I can't figure out how to get it working that way. 

I have defined the prefixes how I want them in `hook_confg_info()`, and adjusted the config load call in `hook_preset_form()` to load from the correct file, but I can't figure out how to get the lading page listing to work as expected. 

Do you have a plan in mind already for how this could work? 

~If not, I was thinking we could perhaps model `hook_config_info()` where the individual-file option has keys for 'name_key' and 'label_key' instad of 'name' and 'label'.~ edit: I found a simpler approach.

**Comment by ghost** [comment]
I hadn't considered putting different instances of `hook_preset_types()` into separate config files. Probably because my only use-case for presets has been srcset Image, and it has only one field per set: https://github.com/backdrop-contrib/srcset_image/blob/694e19ef42d5aceaa74cf1aa992e94a0f6304f51/srcset_image.module#L53

But now considering larger presets, and looking at core image style config, I can see how one config file per preset instance would be ideal in some situations...

Speaking of which @jenlampton, I'd love to know more about your (intended) use of Preset...

**Comment by jenlampton** [comment]
@BWPanda  I am using Preset API for video_embed_field, and my intended implementation is now up in a PR there: 
https://github.com/backdrop-contrib/video_embed_field/pull/20

I'm about to post a PR that adds an `'individual' = TRUE` option for `hook_preset_types()`. Not too many changes were needed to support both options. 

* I added a `preset_get_config()` to pull the all config from the correct location for the admin list.
* I added a check for `$properties['individual']` into the configure form to get the appropriate filename for `$form['#config']` as well as default values.
* I added a check for `$properties['individual']` into the submit handler to determine the correct key for `$config->set()`.

**Comment by ghost** [comment]
If we're going to make it possible to store separate preset instances in separate config files, I think I'd prefer to do that across the board and by default, rather than having it as an option and supporting both ways...

@jenlampton Are you able/willing to change your PR to just change Preset API to store config separately?

**Comment by jenlampton** [comment]
Yes, I can do that! :)

**Comment by laryn** [comment]
@jenlampton Did you ever make progress on this? And if not, can I take over to try to help get this functioning?

**Comment by laryn** [comment]
@BWPanda Do you feel strongly about only supporting separate config files? I've been testing the PR and it's working well. Since there are valid use cases where everything in one config file makes sense (such as the one you had in mind when initially putting this together) I lean towards supporting both -- but I will defer to your judgment and preference if you feel strongly. Or @jenlampton -- do you have any thoughts on this?

**Comment by jenlampton** [comment]
@laryn My preference would be to always have things in separate files since that would make reviewing changes, and doing deploys simpler.

I see that as a benefit even if there is only one setting per file. But I do also see others might prefer config in fewer files, especially if hosting on Pantheon (or anywhere else with external file storage for config). In those cases, however, I would prefer to see a more holistic solution to that problem (like config storage in the database) rather than a fix on a per-config-file basis.

**Comment by laryn** [comment]
@jenlampton Sounds reasonable. Let's go with that approach then. I think we'll need an update hook to split apart any existing "all-in-one" configs.

**Comment by laryn** [comment]
@jenlampton Are you interested in testing this PR, which is based off of your original one with the option for a single config file removed, and also adds an update hook?
https://github.com/backdrop-contrib/preset/pull/15/

**Comment by laryn** [comment]
I did a final test on a sandbox, installing `preset` 1.x-1.x and `srcset_image`, configuring a few srcsets, double checking that they were in a single config file, then testing this 1.x-2.x branch and it successfully split the config into two and everything continued running fine after database updates, so I've merged.
